import type { ChainId, ChainFamily } from "./types";

/**
 * ChainConfig — the single source of truth for every supported network.
 *
 * Each chain carries its RPC endpoint, explorer paths, and the relevant
 * on-chain addresses (or Solana program / Aptos module / Substrate remark
 * extrinsic) used to anchor CIDs. Contract addresses live here and only
 * here — do not duplicate them in per-contract maps.
 */
export interface ChainConfig {
  id: ChainId;
  family: ChainFamily;
  name: string;
  shortName: string;
  rpcUrl: string;
  explorerUrl: string;
  explorerTxPath: string;
  explorerAddressPath: string;
  nativeCurrency: { symbol: string; decimals: number };
  /** Asset key for chain logos; the reference frontend maps it to /chains/*.svg. */
  icon: string;
  registryContract: `0x${string}` | null;
  cacheContract: `0x${string}` | null;
  donationContract: `0x${string}` | null;
  /**
   * Anchor-protocol contracts (propose/verify economics). Optional and only
   * meaningful on contract families (EVM, Aptos, Sui, Starknet, NEAR):
   * `tokenContract` is the FOCAT token that denominates tips, bonds, and
   * validator stakes — the propose path provisions only when it is set (see
   * `isProposeProvisioned`). `stakingContract` / `platformRegistryContract`
   * are ValidatorStaking and PlatformRegistry; `governorContract` /
   * `timelockContract` exist on EVM chains only (governance is EVM-hubbed,
   * other runtimes mirror decisions via admin accounts). On Move chains the
   * registry module address doubles for these where modules share an
   * account. Absent means not deployed.
   */
  tokenContract?: string | null;
  stakingContract?: string | null;
  platformRegistryContract?: string | null;
  governorContract?: string | null;
  timelockContract?: string | null;
  /** Platform id integrators on this chain default to (FileOnChain = "1"). */
  defaultPlatformId?: string;
  programId: string | null;
  /**
   * Deployed on-chain code that `anchor_cid` calls: an Aptos/Sui Move
   * module address, a NEAR contract account, or a TRON registry address.
   */
  moduleAddress: string | null;
  palletContract: string | null;
  /**
   * Anchors ride the chain's native memo / metadata / comment channel — no
   * deployment of ours needed (Cosmos tx memo, TRON memo, Cardano tx
   * metadata, TON transfer comment). Setting this true is the deliberate
   * provisioning switch for those families; flip it per chain after QA.
   */
  memoAnchoring?: boolean;
  /** Bech32 address prefix — Cosmos-family chains only. */
  bech32Prefix?: string | null;
  /** Hedera Consensus Service topic that receives anchor messages. */
  hcsTopicId?: string | null;
  /**
   * Whether chunk anchors on this chain embed the chunk bytes themselves
   * (base64 `d` field). Only data-storage chains (Autonomys) set this;
   * everywhere else anchors are CID-only. Absent means false.
   */
  embedsChunkData?: boolean;
  testnet: boolean;
}

export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000" as const;

/* TODO: deploy address — replace after Foundry Deploy.s.sol runs on each chain */
export const CHAINS: readonly ChainConfig[] = [
  // EVM mainnets
  {
    id: "evm:1",
    family: "evm",
    name: "Ethereum",
    shortName: "ETH",
    rpcUrl: "https://eth.llamarpc.com",
    explorerUrl: "https://etherscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/eth.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:8453",
    family: "evm",
    name: "Base",
    shortName: "BASE",
    rpcUrl: "https://mainnet.base.org",
    explorerUrl: "https://basescan.org",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/base.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:10",
    family: "evm",
    name: "Optimism",
    shortName: "OP",
    rpcUrl: "https://mainnet.optimism.io",
    explorerUrl: "https://optimistic.etherscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/op.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:42161",
    family: "evm",
    name: "Arbitrum One",
    shortName: "ARB",
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    explorerUrl: "https://arbiscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/arb.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:137",
    family: "evm",
    name: "Polygon",
    shortName: "POLY",
    rpcUrl: "https://polygon-rpc.com",
    explorerUrl: "https://polygonscan.com",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "MATIC", decimals: 18 },
    icon: "/chains/polygon.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:56",
    family: "evm",
    name: "BNB Smart Chain",
    shortName: "BNB",
    rpcUrl: "https://bsc-dataseed.bnbchain.org",
    explorerUrl: "https://bscscan.com",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "BNB", decimals: 18 },
    icon: "/chains/bnb.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:43114",
    family: "evm",
    name: "Avalanche C-Chain",
    shortName: "AVAX",
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    explorerUrl: "https://snowtrace.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "AVAX", decimals: 18 },
    icon: "/chains/avalanche.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:324",
    family: "evm",
    name: "zkSync Era",
    shortName: "ZKS",
    rpcUrl: "https://mainnet.era.zksync.io",
    explorerUrl: "https://explorer.zksync.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/zksync.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:534352",
    family: "evm",
    name: "Scroll",
    shortName: "SCR",
    rpcUrl: "https://rpc.scroll.io",
    explorerUrl: "https://scrollscan.com",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/scroll.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:59144",
    family: "evm",
    name: "Linea",
    shortName: "LINEA",
    rpcUrl: "https://rpc.linea.build",
    explorerUrl: "https://lineascan.build",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/linea.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:5000",
    family: "evm",
    name: "Mantle",
    shortName: "MNT",
    rpcUrl: "https://rpc.mantle.xyz",
    explorerUrl: "https://mantlescan.xyz",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "MNT", decimals: 18 },
    icon: "/chains/mantle.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:81457",
    family: "evm",
    name: "Blast",
    shortName: "BLAST",
    rpcUrl: "https://rpc.blast.io",
    explorerUrl: "https://blastscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/blast.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "evm:42220",
    family: "evm",
    name: "Celo",
    shortName: "CELO",
    rpcUrl: "https://forno.celo.org",
    explorerUrl: "https://celoscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "CELO", decimals: 18 },
    icon: "/chains/celo.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  // EVM testnets
  {
    id: "evm:11155111",
    family: "evm",
    name: "Ethereum Sepolia",
    shortName: "SEP",
    rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
    explorerUrl: "https://sepolia.etherscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/eth.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:84532",
    family: "evm",
    name: "Base Sepolia",
    shortName: "BASE",
    rpcUrl: "https://sepolia.base.org",
    explorerUrl: "https://sepolia.basescan.org",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/base.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:11155420",
    family: "evm",
    name: "OP Sepolia",
    shortName: "OP",
    rpcUrl: "https://sepolia.optimism.io",
    explorerUrl: "https://sepolia-optimism.etherscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/op.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:421614",
    family: "evm",
    name: "Arbitrum Sepolia",
    shortName: "ARB",
    rpcUrl: "https://sepolia-rollup.arbitrum.io/rpc",
    explorerUrl: "https://sepolia.arbiscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/arb.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:80002",
    family: "evm",
    name: "Polygon Amoy",
    shortName: "POLY",
    rpcUrl: "https://rpc-amoy.polygon.technology",
    explorerUrl: "https://amoy.polygonscan.com",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "POL", decimals: 18 },
    icon: "/chains/polygon.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:97",
    family: "evm",
    name: "BNB Smart Chain Testnet",
    shortName: "BNB",
    rpcUrl: "https://data-seed-prebsc-1-s1.bnbchain.org:8545",
    explorerUrl: "https://testnet.bscscan.com",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "tBNB", decimals: 18 },
    icon: "/chains/bnb.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:43113",
    family: "evm",
    name: "Avalanche Fuji",
    shortName: "AVAX",
    rpcUrl: "https://api.avax-test.network/ext/bc/C/rpc",
    explorerUrl: "https://testnet.snowtrace.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "AVAX", decimals: 18 },
    icon: "/chains/avalanche.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:300",
    family: "evm",
    name: "zkSync Sepolia",
    shortName: "ZKS",
    rpcUrl: "https://sepolia.era.zksync.dev",
    explorerUrl: "https://sepolia.explorer.zksync.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/zksync.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:534351",
    family: "evm",
    name: "Scroll Sepolia",
    shortName: "SCR",
    rpcUrl: "https://sepolia-rpc.scroll.io",
    explorerUrl: "https://sepolia.scrollscan.com",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/scroll.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:59141",
    family: "evm",
    name: "Linea Sepolia",
    shortName: "LINEA",
    rpcUrl: "https://rpc.sepolia.linea.build",
    explorerUrl: "https://sepolia.lineascan.build",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/linea.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:5003",
    family: "evm",
    name: "Mantle Sepolia",
    shortName: "MNT",
    rpcUrl: "https://rpc.sepolia.mantle.xyz",
    explorerUrl: "https://sepolia.mantlescan.xyz",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "MNT", decimals: 18 },
    icon: "/chains/mantle.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:168587",
    family: "evm",
    name: "Blast Sepolia",
    shortName: "BLAST",
    rpcUrl: "https://sepolia.blast.io",
    explorerUrl: "https://sepolia.blastscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ETH", decimals: 18 },
    icon: "/chains/blast.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  {
    id: "evm:44787",
    family: "evm",
    name: "Celo Alfajores",
    shortName: "CELO",
    rpcUrl: "https://alfajores-forno.celo-testnet.org",
    explorerUrl: "https://alfajores.celoscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "CELO", decimals: 18 },
    icon: "/chains/celo.svg",
    registryContract: ZERO_ADDRESS,
    cacheContract: ZERO_ADDRESS,
    donationContract: ZERO_ADDRESS,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  // Substrate
  {
    id: "substrate:autonomys-mainnet",
    family: "substrate",
    name: "Autonomys Mainnet",
    shortName: "AUTO",
    rpcUrl: "wss://rpc.mainnet.autonomys.xyz/ws",
    explorerUrl: "https://explorer.autonomys.xyz",
    explorerTxPath: "/extrinsic/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "AI3", decimals: 18 },
    icon: "/chains/autonomys.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: "system.remarkWithEvent",
    embedsChunkData: true,
    testnet: false,
  },
  {
    id: "substrate:autonomys-taurus",
    family: "substrate",
    name: "Autonomys Taurus",
    shortName: "TAU",
    rpcUrl: "wss://rpc.taurus.autonomys.xyz/ws",
    explorerUrl: "https://explorer.taurus.autonomys.xyz",
    explorerTxPath: "/extrinsic/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "TAU", decimals: 18 },
    icon: "/chains/autonomys.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: "system.remarkWithEvent",
    embedsChunkData: true,
    testnet: true,
  },
  {
    id: "substrate:polkadot-asset-hub",
    family: "substrate",
    name: "Polkadot Asset Hub",
    shortName: "DOT",
    rpcUrl: "wss://rpc-asset-hub.polkadot.io",
    explorerUrl: "https://assethub-polkadot.subscan.io",
    explorerTxPath: "/extrinsic/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "DOT", decimals: 10 },
    icon: "/chains/polkadot.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: "system.remarkWithEvent",
    testnet: false,
  },
  {
    id: "substrate:kusama-asset-hub",
    family: "substrate",
    name: "Kusama Asset Hub",
    shortName: "KSM",
    rpcUrl: "wss://kusama-asset-hub-rpc.polkadot.io",
    explorerUrl: "https://assethub-kusama.subscan.io",
    explorerTxPath: "/extrinsic/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "KSM", decimals: 12 },
    icon: "/chains/kusama.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: "system.remarkWithEvent",
    testnet: false,
  },
  {
    id: "substrate:westend-asset-hub",
    family: "substrate",
    name: "Westend Asset Hub",
    shortName: "WND",
    rpcUrl: "wss://westend-asset-hub-rpc.polkadot.io",
    explorerUrl: "https://assethub-westend.subscan.io",
    explorerTxPath: "/extrinsic/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "WND", decimals: 12 },
    icon: "/chains/polkadot.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: "system.remarkWithEvent",
    testnet: true,
  },
  {
    id: "substrate:paseo-asset-hub",
    family: "substrate",
    name: "Paseo Asset Hub",
    shortName: "PAS",
    rpcUrl: "wss://asset-hub-paseo-rpc.dwellir.com",
    explorerUrl: "https://assethub-paseo.subscan.io",
    explorerTxPath: "/extrinsic/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "PAS", decimals: 10 },
    icon: "/chains/polkadot.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: "system.remarkWithEvent",
    testnet: true,
  },
  // Solana
  {
    id: "solana:mainnet",
    family: "solana",
    name: "Solana",
    shortName: "SOL",
    rpcUrl: "https://api.mainnet-beta.solana.com",
    explorerUrl: "https://solscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "SOL", decimals: 9 },
    icon: "/chains/solana.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    /* TODO: deploy Solana program for CID anchoring */
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "solana:devnet",
    family: "solana",
    name: "Solana Devnet",
    shortName: "SOL",
    rpcUrl: "https://api.devnet.solana.com",
    explorerUrl: "https://solscan.io",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "SOL", decimals: 9 },
    icon: "/chains/solana.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  // Aptos
  {
    id: "aptos:mainnet",
    family: "aptos",
    name: "Aptos",
    shortName: "APT",
    rpcUrl: "https://fullnode.mainnet.aptoslabs.com/v1",
    explorerUrl: "https://explorer.aptoslabs.com",
    explorerTxPath: "/txn/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "APT", decimals: 8 },
    icon: "/chains/aptos.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    /* TODO: deploy Move module on Aptos for CID anchoring */
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "aptos:testnet",
    family: "aptos",
    name: "Aptos Testnet",
    shortName: "APT",
    rpcUrl: "https://fullnode.testnet.aptoslabs.com/v1",
    explorerUrl: "https://explorer.aptoslabs.com",
    explorerTxPath: "/txn/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "APT", decimals: 8 },
    icon: "/chains/aptos.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  // Cosmos — anchors ride the tx memo; memoAnchoring is the provisioning switch
  {
    id: "cosmos:cosmoshub-4",
    family: "cosmos",
    name: "Cosmos Hub",
    shortName: "ATOM",
    rpcUrl: "https://cosmos-rpc.publicnode.com:443",
    explorerUrl: "https://www.mintscan.io/cosmos",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ATOM", decimals: 6 },
    icon: "/chains/cosmos.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    bech32Prefix: "cosmos",
    testnet: false,
  },
  {
    id: "cosmos:theta-testnet-001",
    family: "cosmos",
    name: "Cosmos Hub Testnet",
    shortName: "ATOM",
    rpcUrl: "https://rpc.sentry-01.theta-testnet.polypore.xyz",
    explorerUrl: "https://explorer.polypore.xyz/theta-testnet-001",
    explorerTxPath: "/transactions/",
    explorerAddressPath: "/accounts/",
    nativeCurrency: { symbol: "ATOM", decimals: 6 },
    icon: "/chains/cosmos.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    memoAnchoring: true,
    bech32Prefix: "cosmos",
    testnet: true,
  },
  // Sui — provisioned once the Move module address lands
  {
    id: "sui:mainnet",
    family: "sui",
    name: "Sui",
    shortName: "SUI",
    rpcUrl: "https://fullnode.mainnet.sui.io:443",
    explorerUrl: "https://suiscan.xyz/mainnet",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "SUI", decimals: 9 },
    icon: "/chains/sui.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    /* TODO: deploy contracts/sui module and set moduleAddress */
    testnet: false,
  },
  {
    id: "sui:testnet",
    family: "sui",
    name: "Sui Testnet",
    shortName: "SUI",
    rpcUrl: "https://fullnode.testnet.sui.io:443",
    explorerUrl: "https://suiscan.xyz/testnet",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "SUI", decimals: 9 },
    icon: "/chains/sui.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  // Starknet — provisioned once the Cairo registry address lands
  {
    id: "starknet:mainnet",
    family: "starknet",
    name: "Starknet",
    shortName: "STRK",
    rpcUrl: "https://starknet-mainnet.public.blastapi.io/rpc/v0_7",
    explorerUrl: "https://starkscan.co",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/contract/",
    nativeCurrency: { symbol: "STRK", decimals: 18 },
    icon: "/chains/starknet.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    /* TODO: deploy contracts/starknet registry and set registryContract */
    testnet: false,
  },
  {
    id: "starknet:sepolia",
    family: "starknet",
    name: "Starknet Sepolia",
    shortName: "STRK",
    rpcUrl: "https://starknet-sepolia.public.blastapi.io/rpc/v0_7",
    explorerUrl: "https://sepolia.starkscan.co",
    explorerTxPath: "/tx/",
    explorerAddressPath: "/contract/",
    nativeCurrency: { symbol: "STRK", decimals: 18 },
    icon: "/chains/starknet.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  // NEAR — moduleAddress holds the registry contract account
  {
    id: "near:mainnet",
    family: "near",
    name: "NEAR",
    shortName: "NEAR",
    rpcUrl: "https://rpc.mainnet.near.org",
    explorerUrl: "https://nearblocks.io",
    explorerTxPath: "/txns/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "NEAR", decimals: 24 },
    icon: "/chains/near.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    /* TODO: deploy contracts/near and set moduleAddress to the contract account */
    testnet: false,
  },
  {
    id: "near:testnet",
    family: "near",
    name: "NEAR Testnet",
    shortName: "NEAR",
    rpcUrl: "https://rpc.testnet.near.org",
    explorerUrl: "https://testnet.nearblocks.io",
    explorerTxPath: "/txns/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "NEAR", decimals: 24 },
    icon: "/chains/near.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: true,
  },
  // TRON — memo MVP; a TVM FileRegistry can land in moduleAddress later
  {
    id: "tron:mainnet",
    family: "tron",
    name: "TRON",
    shortName: "TRX",
    rpcUrl: "https://api.trongrid.io",
    explorerUrl: "https://tronscan.org",
    explorerTxPath: "/#/transaction/",
    explorerAddressPath: "/#/address/",
    nativeCurrency: { symbol: "TRX", decimals: 6 },
    icon: "/chains/tron.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "tron:nile",
    family: "tron",
    name: "TRON Nile",
    shortName: "TRX",
    rpcUrl: "https://nile.trongrid.io",
    explorerUrl: "https://nile.tronscan.org",
    explorerTxPath: "/#/transaction/",
    explorerAddressPath: "/#/address/",
    nativeCurrency: { symbol: "TRX", decimals: 6 },
    icon: "/chains/tron.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    memoAnchoring: true,
    testnet: true,
  },
  // Cardano — metadata-only MVP (no Plutus); rpcUrl expects a Blockfrost-compatible API
  {
    id: "cardano:mainnet",
    family: "cardano",
    name: "Cardano",
    shortName: "ADA",
    rpcUrl: "https://cardano-mainnet.blockfrost.io/api/v0",
    explorerUrl: "https://cardanoscan.io",
    explorerTxPath: "/transaction/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ADA", decimals: 6 },
    icon: "/chains/cardano.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "cardano:preprod",
    family: "cardano",
    name: "Cardano Preprod",
    shortName: "ADA",
    rpcUrl: "https://cardano-preprod.blockfrost.io/api/v0",
    explorerUrl: "https://preprod.cardanoscan.io",
    explorerTxPath: "/transaction/",
    explorerAddressPath: "/address/",
    nativeCurrency: { symbol: "ADA", decimals: 6 },
    icon: "/chains/cardano.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    memoAnchoring: true,
    testnet: true,
  },
  // TON — anchors ride transfer comments via TON Connect
  {
    id: "ton:mainnet",
    family: "ton",
    name: "TON",
    shortName: "TON",
    rpcUrl: "https://toncenter.com/api/v2/jsonRPC",
    explorerUrl: "https://tonviewer.com",
    explorerTxPath: "/transaction/",
    explorerAddressPath: "/",
    nativeCurrency: { symbol: "TON", decimals: 9 },
    icon: "/chains/ton.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    testnet: false,
  },
  {
    id: "ton:testnet",
    family: "ton",
    name: "TON Testnet",
    shortName: "TON",
    rpcUrl: "https://testnet.toncenter.com/api/v2/jsonRPC",
    explorerUrl: "https://testnet.tonviewer.com",
    explorerTxPath: "/transaction/",
    explorerAddressPath: "/",
    nativeCurrency: { symbol: "TON", decimals: 9 },
    icon: "/chains/ton.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    memoAnchoring: true,
    testnet: true,
  },
  // Hedera — anchors are HCS messages; hcsTopicId is the provisioning switch
  {
    id: "hedera:mainnet",
    family: "hedera",
    name: "Hedera",
    shortName: "HBAR",
    rpcUrl: "https://mainnet.mirrornode.hedera.com",
    explorerUrl: "https://hashscan.io/mainnet",
    explorerTxPath: "/transaction/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "HBAR", decimals: 8 },
    icon: "/chains/hedera.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    /* TODO: create an HCS topic (docs/deploy/hedera.md) and set hcsTopicId */
    hcsTopicId: null,
    testnet: false,
  },
  {
    id: "hedera:testnet",
    family: "hedera",
    name: "Hedera Testnet",
    shortName: "HBAR",
    rpcUrl: "https://testnet.mirrornode.hedera.com",
    explorerUrl: "https://hashscan.io/testnet",
    explorerTxPath: "/transaction/",
    explorerAddressPath: "/account/",
    nativeCurrency: { symbol: "HBAR", decimals: 8 },
    icon: "/chains/hedera.svg",
    registryContract: null,
    cacheContract: null,
    donationContract: null,
    programId: null,
    moduleAddress: null,
    palletContract: null,
    hcsTopicId: null,
    testnet: true,
  },
] as const;

export const DEFAULT_CHAIN_ID: ChainId = "substrate:autonomys-mainnet";

export const getChain = (id: ChainId | string): ChainConfig | undefined =>
  CHAINS.find((c) => c.id === id);

export const getChainsByFamily = (family: ChainFamily): ChainConfig[] =>
  CHAINS.filter((c) => c.family === family);

/** Production networks only — marketing surfaces count these. */
export const MAINNET_CHAINS: readonly ChainConfig[] = CHAINS.filter(
  (c) => !c.testnet,
);

export const TESTNET_CHAINS: readonly ChainConfig[] = CHAINS.filter(
  (c) => c.testnet,
);

/**
 * Chains a picker should offer given the user's testnet-visibility
 * preference. Keeps the "hide testnets" rule in one place.
 */
export const getVisibleChains = (showTestnets: boolean): readonly ChainConfig[] =>
  showTestnets ? CHAINS : MAINNET_CHAINS;

/**
 * Pick the registry address for a chain, falling back to the zero address.
 */
export const getRegistryAddress = (chainId: ChainId): `0x${string}` =>
  getChain(chainId)?.registryContract ?? ZERO_ADDRESS;

/**
 * Display labels for each chain runtime — used by every surface that
 * groups chains (chain switcher, explorer filters, chains grid). The
 * intent is to surface the architecture plainly so a user can tell a
 * "Base" address apart from a "Solana" address without learning the
 * internal "family" word.
 */
export const CHAIN_FAMILY_LABELS: Record<ChainFamily, string> = {
  evm: "EVM-compatible",
  substrate: "Substrate-based",
  solana: "Solana",
  aptos: "Aptos",
  cosmos: "Cosmos",
  sui: "Sui",
  starknet: "Starknet",
  near: "NEAR",
  tron: "TRON",
  cardano: "Cardano",
  ton: "TON",
  hedera: "Hedera",
};

/**
 * Short tagline that explains the difference between EVM-compatible and
 * Solana / Aptos in one line. Surfaced in the explorer filter tooltip
 * and the onboarding flow.
 */
export const CHAIN_FAMILY_TAGLINES: Record<ChainFamily, string> = {
  evm: "Same Ethereum tooling, different network.",
  substrate: "Uses Substrate's `system.remark` as the on-chain storage primitive.",
  solana: "Programs instead of contracts. Use a Solana wallet.",
  aptos: "Move modules. Use an Aptos wallet.",
  cosmos: "IBC app-chains; anchors ride the transaction memo. Use Keplr or Leap.",
  sui: "Move objects and PTBs — separate from Aptos. Use a Sui wallet.",
  starknet: "Cairo contracts on a ZK rollup. Use Argent or Braavos.",
  near: "Human-readable accounts and WASM contracts. Use a NEAR wallet.",
  tron: "TVM contracts with TRON addressing. Use TronLink.",
  cardano: "Anchors ride transaction metadata. Use a CIP-30 wallet like Lace.",
  ton: "Anchors ride transfer comments. Use a TON Connect wallet.",
  hedera:
    "Anchors are Consensus Service messages — a small fixed topic fee instead of gas. Use HashPack.",
};

/** Every chain family, in display order — UI surfaces that enumerate
 * runtimes (filters, grids, switchers) iterate this, never a local list. */
export const CHAIN_FAMILIES = Object.keys(CHAIN_FAMILY_LABELS) as readonly ChainFamily[];

/**
 * Build an explorer link for a tx hash.
 */
export const buildTxUrl = (chain: ChainConfig, txHash: string): string =>
  `${chain.explorerUrl}${chain.explorerTxPath}${txHash}`;

/**
 * Build an explorer link for an address or contract.
 */
export const buildAddressUrl = (chain: ChainConfig, address: string): string =>
  `${chain.explorerUrl}${chain.explorerAddressPath}${address}`;
